### PR TITLE
Port purescript-corefn to spago and PureScript 0.13

### PR DESCRIPTION
**Pull request by jbmusso**
Greetings,
I just noticed that there's ongoing work on this branch related to porting this library to PureScript 0.13.
Cloned locally, I was able to build and run tests (from nix-shell).

Would you see something more specific that should be tackled before this gets merged into master? We'd be happy to help.

### CODE REVIEW

**Comment by jbmusso** [comment]
Just fixed Travis CI on my fork. I opened this PR using your branch and I can't push my commits there: feel free to `cherry-pick` https://github.com/tcmlabs/purescript-corefn/pull/1/commits/b4d629e4fff65fa62489b895f89bf13be5cf725e

**Comment by paulyoung** [comment]
Sorry for the delay on this. Do you think your changes are still good to merge in?

**Comment by jbmusso** [comment]
No problem. I think the PR is fine, but I should open it on this repo instead.

**Comment by paulyoung** [comment]
Closing since #61 was merged instead.

**Pull request closed without merging**
